server:
  port: 8081
  servlet:
    context-path: /handle

spring:
  application:
    name: uros-handle
  
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    com.uros.kernel.handle: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 自定义配置
handle:
  id: "handle-app-001"  # Handle应用实例的唯一标识符
  api:
    base-path: /api
    version: v1
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
